// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeURL(arg1) {
  return window['go']['main']['App']['AnalyzeURL'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CancelProviderAuth(arg1) {
  return window['go']['main']['App']['CancelProviderAuth'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyDiagnostic() {
  return window['go']['main']['App']['CopyDiagnostic']();
}

export function Diagnostic() {
  return window['go']['main']['App']['Diagnostic']();
}

export function DisconnectProvider(arg1) {
  return window['go']['main']['App']['DisconnectProvider'](arg1);
}

export function GetEngineStatus() {
  return window['go']['main']['App']['GetEngineStatus']();
}

export function GetProviderAuthStatus(arg1) {
  return window['go']['main']['App']['GetProviderAuthStatus'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenDownloadFolder(arg1) {
  return window['go']['main']['App']['OpenDownloadFolder'](arg1);
}

export function OpenDownloadedFile(arg1) {
  return window['go']['main']['App']['OpenDownloadedFile'](arg1);
}

export function OpenGitHubIssues() {
  return window['go']['main']['App']['OpenGitHubIssues']();
}

export function OpenRelease(arg1) {
  return window['go']['main']['App']['OpenRelease'](arg1);
}

export function RecentDownloads(arg1) {
  return window['go']['main']['App']['RecentDownloads'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectAppleMusicCookies() {
  return window['go']['main']['App']['SelectAppleMusicCookies']();
}

export function SelectDownloadDirectory() {
  return window['go']['main']['App']['SelectDownloadDirectory']();
}

export function SelectProviderCookies(arg1) {
  return window['go']['main']['App']['SelectProviderCookies'](arg1);
}

export function SetWindowFocused(arg1) {
  return window['go']['main']['App']['SetWindowFocused'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartProviderAuth(arg1) {
  return window['go']['main']['App']['StartProviderAuth'](arg1);
}

export function UpdateEngines() {
  return window['go']['main']['App']['UpdateEngines']();
}

export function VerifyProviderAuth(arg1) {
  return window['go']['main']['App']['VerifyProviderAuth'](arg1);
}
