// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAppleMusic(arg1, arg2, arg3) {
  return ObfuscatedCall(0, [arg1, arg2, arg3]);
}

export function DownloadYoutube(arg1, arg2, arg3) {
  return ObfuscatedCall(1, [arg1, arg2, arg3]);
}
