// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeURL(arg1:string):Promise<models.AnalyzeResponse>;

export function CancelDownload(arg1:string):Promise<models.ActionResponse>;

export function CancelProviderAuth(arg1:models.Service):Promise<models.ProviderAuthStatus>;

export function CheckForUpdate():Promise<models.UpdateResponse>;

export function ClearHistory():Promise<models.ActionResponse>;

export function CopyDiagnostic():Promise<models.ActionResponse>;

export function Diagnostic():Promise<models.DiagnosticResponse>;

export function DisconnectProvider(arg1:models.Service):Promise<models.ProviderAuthStatus>;

export function GetEngineStatus():Promise<models.EngineResponse>;

export function GetProviderAuthStatus(arg1:models.Service):Promise<models.ProviderAuthStatus>;

export function GetSettings():Promise<models.SettingsView>;

export function OpenDownloadFolder(arg1:string):Promise<models.ActionResponse>;

export function OpenDownloadedFile(arg1:string):Promise<models.ActionResponse>;

export function OpenGitHubIssues():Promise<models.ActionResponse>;

export function OpenRelease(arg1:string):Promise<models.ActionResponse>;

export function RecentDownloads(arg1:number):Promise<models.HistoryResponse>;

export function SaveSettings(arg1:models.SettingsView):Promise<models.ActionResponse>;

export function SelectAppleMusicCookies():Promise<models.ActionResponse>;

export function SelectDownloadDirectory():Promise<models.ActionResponse>;

export function SelectProviderCookies(arg1:models.Service):Promise<models.ActionResponse>;

export function SetWindowFocused(arg1:boolean):Promise<void>;

export function StartDownload(arg1:models.DownloadRequest):Promise<models.StartDownloadResponse>;

export function StartProviderAuth(arg1:models.Service):Promise<models.ProviderAuthStatus>;

export function UpdateEngines():Promise<models.EngineResponse>;

export function VerifyProviderAuth(arg1:models.Service):Promise<models.ProviderAuthStatus>;
